app:
  system: "base-project"

server:
  port: 8080

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] [%-5level] %logger{36} - [%mdc] %msg%n"
    file: "%d{HH:mm:ss.SSS} [%thread] [%-5level] %logger{36} - [%mdc] %msg%n"
  file:
    path: ./log
    name: ${logging.file.path}/application.log
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 7
  level:
    root: ERROR
    ru.dorofeev: DEBUG
    orb.hibernate.SQL: ERROR
    org.springframework.transaction: ERROR
    org.springframework.security: ERROR
    org.springframework.cache: ERROR

spring:
  main:
    banner-mode: OFF
  profiles:
    default: default
    include:
      - security
  config:
    import: optional:file:docker/.env[.properties]
  datasource:
    url: ${POSTGRES_HOST}/${POSTGRES_DB}?prepareThreshold=0&targetServerType=primary
    username: ${POSTGRES_USR}
    password: ${POSTGRES_PWD}
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
  liquibase:
    enabled: true
    change-log: classpath:liquibase/changelog/changelog.yaml
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_batch_fetch_size: 25
        batch_fetch_style: dynamic
        query:
          fail_on_pagination_over_collection_fetch: true

management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: when_authorized
  endpoints:
    web:
      exposure:
        include: health, prometheus, sessions
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true

springdoc:
  api-docs:
    enabled: false

http-client:
  timeout:
    read: 30000
    write: 30000
    connection: 5000
