server:
  port: 8081
  servlet:
    session:
      cookie:
        path: "/"
        secure: false

spring:
  datasource:
    url: ${LOCAL_POSTGRES_HOST}/${LOCAL_POSTGRES_DB}?prepareThreshold=0&targetServerType=primary
    username: ${LOCAL_POSTGRES_USR}
    password: ${LOCAL_POSTGRES_PWD}

springdoc:
  api-docs:
    enabled: true

management:
  endpoint:
    health:
      show-details: always

security:
  endpoint:
    white-list:
      - "/actuator/**"
      - "/v3/api-docs"
      - "/v3/api-docs.yaml"
      - "/swagger-ui/**"
      - "/authentication/login"
      - "/authentication/registration"
      - "/authentication/password/reset"
      - "/settings/pre-login"
      - "/public/**"
  cors:
    allowed-origins:
      - "http://localhost:3000"

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.web.csrf: TRACE
    org.springframework.web: DEBUG
    org.springframework.session: DEBUG
    org.hibernate:
      SQL: DEBUG
      type.descriptor.sql.BasicBinder: TRACE
    ru.dorofeev: DEBUG
