name: Java CI with Gradle
on:
  push:
    branches:
      - 'main'
      - 'develop'
      - 'releases/*'
      - 'hotfix/*'
    paths:
      - 'back/**'
      - '.github/workflows/backend.yml'
  pull_request:
    branches:
      - 'main'
      - 'develop'
      - 'releases/*'
      - 'hotfix/*'
    paths:
      - 'back/**'
      - '.github/workflows/backend.yml'

permissions:
  contents: read

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Make gradlew executable (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: chmod +x ./gradlew
        #Caching is enabled by default when using the gradle/gradle-build-action action
      - name: Setup and execute Gradle 'build' task
        uses: gradle/gradle-build-action@v3
        with:
          arguments: build -x test
      - name: Make gradlew executable (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: chmod +x ./gradlew
      - name: Setup and execute Gradle 'test' task
        uses: gradle/gradle-build-action@v3
        with:
          arguments: test
  package-artifact:
    needs: build-and-test
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Make gradlew executable (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: chmod +x ./gradlew
      - name: Setup and execute Gradle 'bootJar' task
        uses: gradle/gradle-build-action@v3
        with:
          arguments: bootJar
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: application-${{ matrix.os }}
          path: ./back/business-application/build/libs
          retention-days: 1
          if-no-files-found: error